-- Lich QC duoc phan cong rieng, khong tao snapshot/khong khoa kho.
ALTER TABLE DotKiemKe
  ADD COLUMN LoaiDot VARCHAR(20) NOT NULL DEFAULT 'COUNT',
  ADD COLUMN LoaiKiemTra VARCHAR(20) NULL,
  ADD COLUMN DiaDiem VARCHAR(500) NULL,
  ADD CONSTRAINT KiemTra_DotKiemKe_LoaiDot CHECK (LoaiDot IN ('COUNT','QUALITY_CHECK')),
  ADD CONSTRAINT KiemTra_DotKiemKe_LoaiKiemTra CHECK (LoaiKiemTra IS NULL OR LoaiKiemTra IN ('MATERIAL','FINISHED_PRODUCT'));

CREATE TABLE LoLichKiemTra (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLichKiemTra BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_LoLichKiemTra UNIQUE (MaLichKiemTra,MaLoHang),
  CONSTRAINT KhoaNgoai_LoLichKiemTra_DotKiemKe FOREIGN KEY (MaLichKiemTra) REFERENCES DotKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_LoLichKiemTra_LoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE PhanCongLichKiemTra (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLichKiemTra BIGINT UNSIGNED NOT NULL,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_PhanCongLichKiemTra UNIQUE (MaLichKiemTra,MaNguoiDung),
  CONSTRAINT KhoaNgoai_PhanCongLichKiemTra_DotKiemKe FOREIGN KEY (MaLichKiemTra) REFERENCES DotKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongLichKiemTra_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;

ALTER TABLE PhieuKiemTraChatLuong
  ADD COLUMN MaLichKiemTra BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KhoaNgoai_PhieuKiemTraChatLuong_Lich FOREIGN KEY (MaLichKiemTra) REFERENCES DotKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;
