-- Nguon yeu cau bo sung NVL, phan cong kho va ho so tong hop.
ALTER TABLE YeuCauKho
  DROP CHECK KiemTra_YeuCauKho_2,
  ADD COLUMN MaBaoCaoSanXuat BIGINT UNSIGNED NULL,
  ADD COLUMN MaNguoiPhuTrach BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KiemTra_YeuCauKho_Nguon CHECK (
    (PhuongThuc='PURCHASE_RECEIPT' AND Kieu='IN' AND MaDonMuaHang IS NOT NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NULL AND MaBaoCaoSanXuat IS NULL)
    OR (PhuongThuc='SALE_ISSUE' AND Kieu='OUT' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NOT NULL AND MaKeHoachSanXuat IS NULL AND MaBaoCaoSanXuat IS NULL)
    OR (PhuongThuc='PRODUCTION_ISSUE' AND Kieu='OUT' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NOT NULL AND MaBaoCaoSanXuat IS NULL)
    OR (PhuongThuc='PRODUCTION_RECEIPT' AND Kieu='IN' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NOT NULL AND MaBaoCaoSanXuat IS NULL)
    OR (PhuongThuc='MATERIAL_PURCHASE' AND Kieu='PROCUREMENT' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NULL AND MaBaoCaoSanXuat IS NOT NULL)
  ),
  ADD CONSTRAINT KhoaNgoai_YeuCauKho_BaoCao FOREIGN KEY (MaBaoCaoSanXuat) REFERENCES BaoCaoSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT KhoaNgoai_YeuCauKho_NguoiPhuTrach FOREIGN KEY (MaNguoiPhuTrach) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh
  ADD COLUMN MaYeuCauNguon BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_YeuCauNguon FOREIGN KEY (MaYeuCauNguon) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CongViec
  ADD COLUMN MaYeuCauKho BIGINT UNSIGNED NULL,
  ADD COLUMN LoaiCongViec VARCHAR(30) NULL,
  ADD COLUMN MaNguoiPhuTrach BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KhoaNgoai_CongViec_YeuCauKho FOREIGN KEY (MaYeuCauKho) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT KhoaNgoai_CongViec_NguoiPhuTrach FOREIGN KEY (MaNguoiPhuTrach) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE PhanCongKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaCongViec BIGINT UNSIGNED NOT NULL,
  MaChiTietYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  NhomChatLuong VARCHAR(20) NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  SoLuongDaGhi DECIMAL(18,3) NOT NULL DEFAULT 0,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_PhanCongKho_SoLuong CHECK (SoLuong>0 AND SoLuongDaGhi>=0 AND SoLuongDaGhi<=SoLuong),
  CONSTRAINT KiemTra_PhanCongKho_ChatLuong CHECK (NhomChatLuong='AVAILABLE'),
  CONSTRAINT KhoaNgoai_PhanCongKho_YeuCauKho FOREIGN KEY (MaYeuCauKho) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongKho_CongViec FOREIGN KEY (MaCongViec) REFERENCES CongViec(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongKho_Dong FOREIGN KEY (MaChiTietYeuCauKho) REFERENCES ChiTietYeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongKho_Nguoi FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongKho_Lo FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_PhanCongKho_ViTri FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  INDEX ChiMuc_PhanCongKho_YeuCau (MaYeuCauKho,MaChiTietYeuCauKho),
  INDEX ChiMuc_PhanCongKho_Ton (MaLoHang,MaViTriKho,NhomChatLuong)
) ENGINE=InnoDB;

ALTER TABLE PhieuKho
  ADD COLUMN MaCongViec BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KhoaNgoai_PhieuKho_CongViec FOREIGN KEY (MaCongViec) REFERENCES CongViec(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietPhieuKho
  ADD COLUMN MaPhanCongKho BIGINT UNSIGNED NULL,
  ADD CONSTRAINT KhoaNgoai_ChiTietPhieuKho_PhanCong FOREIGN KEY (MaPhanCongKho) REFERENCES PhanCongKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE HoSoKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaNguoiPhuTrach BIGINT UNSIGNED NOT NULL,
  GhiChu TEXT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_HoSoKho_YeuCau UNIQUE (MaYeuCauKho),
  CONSTRAINT KhoaNgoai_HoSoKho_YeuCau FOREIGN KEY (MaYeuCauKho) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT KhoaNgoai_HoSoKho_Nguoi FOREIGN KEY (MaNguoiPhuTrach) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB;
