-- Schema MySQL 8.4 cho database KhoHang duy nhất của ứng dụng.
-- Nguồn: docs/DATABASE.md; tên bảng, cột, ràng buộc tiếng Việt không dấu.
-- Docker tự chạy schema trên database KhoHang trống khi khởi động lần đầu.
-- Không import lại vào database đã có bảng; không có DROP TABLE hay seed.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE NguoiDung (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TenDangNhap VARCHAR(80) NOT NULL,
  MatKhauBam VARCHAR(255) NOT NULL,
  HoTen VARCHAR(150) NOT NULL,
  ThuDienTu VARCHAR(254) NULL,
  TrangThai VARCHAR(20) NOT NULL,
  SoLanDangNhapSai INT NOT NULL,
  KhoaDen DATETIME(6) NULL,
  PhienBanPhien INT NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_NguoiDung_1 CHECK (TrangThai IN ('ACTIVE','LOCKED')),
  CONSTRAINT KiemTra_NguoiDung_2 CHECK (SoLanDangNhapSai >= 0),
  CONSTRAINT DuyNhat_NguoiDung_1 UNIQUE (TenDangNhap),
  CONSTRAINT DuyNhat_NguoiDung_2 UNIQUE (ThuDienTu)
) ENGINE=InnoDB;

CREATE TABLE VaiTro (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(100) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_VaiTro_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE NguoiDungVaiTro (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  MaVaiTro BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_NguoiDungVaiTro_1 UNIQUE (MaNguoiDung, MaVaiTro)
) ENGINE=InnoDB;

CREATE TABLE KhachHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  SoDienTho VARCHAR(20) NULL,
  DiaChi VARCHAR(500) NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_KhachHang_1 UNIQUE (MaNguoiDung),
  CONSTRAINT DuyNhat_KhachHang_2 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE Xuong (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  DiaChi VARCHAR(500) NULL,
  ConHoatDong BOOLEAN NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_Xuong_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE NguoiDungXuong (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaXuong BIGINT UNSIGNED NOT NULL,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_NguoiDungXuong_1 UNIQUE (MaXuong, MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE NhaCungCap (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  SoDienTho VARCHAR(20) NULL,
  ThuDienTu VARCHAR(254) NULL,
  DiaChi VARCHAR(500) NULL,
  MaSoThue VARCHAR(30) NULL,
  ConHoatDong BOOLEAN NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_NhaCungCap_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE Kho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  DiaChi VARCHAR(500) NULL,
  ConHoatDong BOOLEAN NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_Kho_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE ViTriKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKho BIGINT UNSIGNED NOT NULL,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  ConHoatDong BOOLEAN NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_ViTriKho_1 UNIQUE (MaKho, Ma)
) ENGINE=InnoDB;

CREATE TABLE LoaiHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  MoTa TEXT NULL,
  ConHoatDong BOOLEAN NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_LoaiHang_1 UNIQUE (Ma),
  CONSTRAINT DuyNhat_LoaiHang_2 UNIQUE (Ten)
) ENGINE=InnoDB;

CREATE TABLE DonViTinh (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(20) NOT NULL,
  Ten VARCHAR(80) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_DonViTinh_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE MatHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLoaiHang BIGINT UNSIGNED NOT NULL,
  MaDonViTinh BIGINT UNSIGNED NOT NULL,
  Ma VARCHAR(40) NOT NULL,
  Ten VARCHAR(150) NOT NULL,
  Loai VARCHAR(20) NOT NULL,
  MoTa TEXT NULL,
  DonGiaThamKhao DECIMAL(19,4) NOT NULL,
  LaHangMau BOOLEAN NOT NULL,
  DuongDanAnh VARCHAR(500) NULL,
  DaCongBo BOOLEAN NOT NULL,
  ConHoatDong BOOLEAN NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_MatHang_1 CHECK (Loai IN ('MATERIAL','FINISHED_PRODUCT')),
  CONSTRAINT KiemTra_MatHang_2 CHECK (DonGiaThamKhao >= 0),
  CONSTRAINT DuyNhat_MatHang_1 UNIQUE (Ma),
  CONSTRAINT DuyNhat_MatHang_2 UNIQUE (MaLoaiHang, Ten)
) ENGINE=InnoDB;

CREATE TABLE DonHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaKhachHang BIGINT UNSIGNED NOT NULL,
  DiaChiGiaoHang VARCHAR(500) NOT NULL,
  NgayGiaoChamNhat DATE NOT NULL,
  GhiChu TEXT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  MaNguoiTiepNhan BIGINT UNSIGNED NULL,
  NgayTiepNhan DATETIME(6) NULL,
  MaNguoiDuyet BIGINT UNSIGNED NULL,
  NgayDuyet DATETIME(6) NULL,
  LyDoTuChoi TEXT NULL,
  TongTienBaoGia DECIMAL(19,4) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_DonHang_1 CHECK (TrangThai IN ('SUBMITTED','RECEIVED','APPROVED','REJECTED','IN_PROGRESS','COMPLETED')),
  CONSTRAINT KiemTra_DonHang_2 CHECK (TongTienBaoGia >= 0),
  CONSTRAINT DuyNhat_DonHang_1 UNIQUE (Ma),
  INDEX ChiMuc_DonHang_1 (MaKhachHang, TrangThai, NgayTao),
  INDEX ChiMuc_DonHang_2 (TrangThai, NgayTao)
) ENGINE=InnoDB;

CREATE TABLE ChiTietDonHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaDonHang BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  DonGia DECIMAL(19,4) NOT NULL,
  GhiChu TEXT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietDonHang_1 CHECK (SoLuong > 0),
  CONSTRAINT KiemTra_ChiTietDonHang_2 CHECK (DonGia >= 0),
  CONSTRAINT DuyNhat_ChiTietDonHang_1 UNIQUE (MaDonHang, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE KeHoachKinhDoanh (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Kieu VARCHAR(10) NOT NULL,
  MaNhaCungCap BIGINT UNSIGNED NULL,
  MaKhachHang BIGINT UNSIGNED NULL,
  MaDonHang BIGINT UNSIGNED NULL,
  NgayDuKien DATE NOT NULL,
  GhiChu TEXT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  MaNguoiDuyet BIGINT UNSIGNED NULL,
  NgayDuyet DATETIME(6) NULL,
  LyDoTuChoi TEXT NULL,
  TongTien DECIMAL(19,4) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_KeHoachKinhDoanh_1 CHECK (Kieu IN ('PURCHASE','SALE')),
  CONSTRAINT KiemTra_KeHoachKinhDoanh_2 CHECK (TrangThai IN ('PENDING_APPROVAL','APPROVED','REJECTED','IN_PROGRESS','COMPLETED','CANCELLED')),
  CONSTRAINT KiemTra_KeHoachKinhDoanh_3 CHECK (TongTien >= 0),
  CONSTRAINT KiemTra_KeHoachKinhDoanh_4 CHECK ((Kieu='PURCHASE' AND MaNhaCungCap IS NOT NULL AND MaKhachHang IS NULL AND MaDonHang IS NULL) OR (Kieu='SALE' AND MaNhaCungCap IS NULL AND MaKhachHang IS NOT NULL AND MaDonHang IS NOT NULL)),
  CONSTRAINT DuyNhat_KeHoachKinhDoanh_1 UNIQUE (Ma),
  INDEX ChiMuc_KeHoachKinhDoanh_1 (Kieu, TrangThai, NgayDuKien)
) ENGINE=InnoDB;

CREATE TABLE ChiTietKeHoachKinhDoanh (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKeHoachKinhDoanh BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  DonGia DECIMAL(19,4) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietKeHoachKinhDoanh_1 CHECK (SoLuong > 0),
  CONSTRAINT KiemTra_ChiTietKeHoachKinhDoanh_2 CHECK (DonGia >= 0),
  CONSTRAINT DuyNhat_ChiTietKeHoachKinhDoanh_1 UNIQUE (MaKeHoachKinhDoanh, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE DonMuaHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaKeHoachKinhDoanh BIGINT UNSIGNED NOT NULL,
  MaNhaCungCap BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  NgayGiaoDuKien DATE NOT NULL,
  DieuKhoanGiaoHang TEXT NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  TongTien DECIMAL(19,4) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_DonMuaHang_1 CHECK (TrangThai IN ('PENDING','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
  CONSTRAINT KiemTra_DonMuaHang_2 CHECK (TongTien >= 0),
  CONSTRAINT DuyNhat_DonMuaHang_1 UNIQUE (Ma),
  CONSTRAINT DuyNhat_DonMuaHang_2 UNIQUE (MaKeHoachKinhDoanh)
) ENGINE=InnoDB;

CREATE TABLE ChiTietDonMuaHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaDonMuaHang BIGINT UNSIGNED NOT NULL,
  MaChiTietKeHoachKinhDoanh BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  DonGia DECIMAL(19,4) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietDonMuaHang_1 CHECK (SoLuong > 0),
  CONSTRAINT KiemTra_ChiTietDonMuaHang_2 CHECK (DonGia >= 0),
  CONSTRAINT DuyNhat_ChiTietDonMuaHang_1 UNIQUE (MaDonMuaHang, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE KeHoachSanXuat (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaDonHang BIGINT UNSIGNED NOT NULL,
  MaXuong BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  NgayBatDau DATE NOT NULL,
  NgayKetThuc DATE NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_KeHoachSanXuat_1 CHECK (NgayKetThuc >= NgayBatDau),
  CONSTRAINT KiemTra_KeHoachSanXuat_2 CHECK (TrangThai IN ('DRAFT','APPROVED','IN_PROGRESS','COMPLETED','CANCELLED')),
  CONSTRAINT DuyNhat_KeHoachSanXuat_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE ThanhPhamKeHoach (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKeHoachSanXuat BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ThanhPhamKeHoach_1 CHECK (SoLuong > 0),
  CONSTRAINT DuyNhat_ThanhPhamKeHoach_1 UNIQUE (MaKeHoachSanXuat, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE NguyenLieuKeHoach (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKeHoachSanXuat BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuongCan DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_NguyenLieuKeHoach_1 CHECK (SoLuongCan > 0),
  CONSTRAINT DuyNhat_NguyenLieuKeHoach_1 UNIQUE (MaKeHoachSanXuat, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE LoHang (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(50) NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  MaChiTietDonMuaHang BIGINT UNSIGNED NULL,
  MaKeHoachSanXuat BIGINT UNSIGNED NULL,
  NgaySanXuat DATE NULL,
  HanSuDung DATE NULL,
  SoLuongNhan DECIMAL(18,3) NOT NULL,
  TrangThaiKiemTra VARCHAR(20) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_LoHang_1 CHECK (SoLuongNhan > 0),
  CONSTRAINT KiemTra_LoHang_2 CHECK (TrangThaiKiemTra IN ('PENDING','PASSED','PARTIAL','FAILED')),
  CONSTRAINT KiemTra_LoHang_3 CHECK (HanSuDung IS NULL OR NgaySanXuat IS NULL OR HanSuDung >= NgaySanXuat),
  CONSTRAINT KiemTra_LoHang_4 CHECK ((MaChiTietDonMuaHang IS NOT NULL AND MaKeHoachSanXuat IS NULL) OR (MaChiTietDonMuaHang IS NULL AND MaKeHoachSanXuat IS NOT NULL)),
  CONSTRAINT DuyNhat_LoHang_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE PhieuKiemTraChatLuong (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaNguoiKiemTra BIGINT UNSIGNED NOT NULL,
  NgayKiemTra DATETIME(6) NOT NULL,
  GhiChu TEXT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_PhieuKiemTraChatLuong_1 CHECK (TrangThai IN ('RECORDED','VOID')),
  CONSTRAINT DuyNhat_PhieuKiemTraChatLuong_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE ChiTietKiemTraChatLuong (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaPhieuKiemTraChatLuong BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  SoLuongKiemTra DECIMAL(18,3) NOT NULL,
  SoLuongDat DECIMAL(18,3) NOT NULL,
  SoLuongLoi DECIMAL(18,3) NOT NULL,
  Loi TEXT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietKiemTraChatLuong_1 CHECK (SoLuongKiemTra > 0),
  CONSTRAINT KiemTra_ChiTietKiemTraChatLuong_2 CHECK (SoLuongDat >= 0),
  CONSTRAINT KiemTra_ChiTietKiemTraChatLuong_3 CHECK (SoLuongLoi >= 0),
  CONSTRAINT KiemTra_ChiTietKiemTraChatLuong_4 CHECK (SoLuongKiemTra = SoLuongDat + SoLuongLoi),
  CONSTRAINT DuyNhat_ChiTietKiemTraChatLuong_1 UNIQUE (MaPhieuKiemTraChatLuong, MaLoHang),
  CONSTRAINT DuyNhat_ChiTietKiemTraChatLuong_2 UNIQUE (MaLoHang)
) ENGINE=InnoDB;

CREATE TABLE YeuCauKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Kieu VARCHAR(10) NOT NULL,
  PhuongThuc VARCHAR(30) NOT NULL,
  MaDonMuaHang BIGINT UNSIGNED NULL,
  MaKeHoachKinhDoanh BIGINT UNSIGNED NULL,
  MaKeHoachSanXuat BIGINT UNSIGNED NULL,
  MaXuong BIGINT UNSIGNED NOT NULL,
  MaKho BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  NgayYeuCau DATE NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  GhiChu TEXT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_YeuCauKho_1 CHECK (TrangThai IN ('PENDING','PARTIALLY_FULFILLED','FULFILLED','CANCELLED')),
  CONSTRAINT KiemTra_YeuCauKho_2 CHECK ((PhuongThuc='PURCHASE_RECEIPT' AND Kieu='IN' AND MaDonMuaHang IS NOT NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NULL) OR (PhuongThuc='SALE_ISSUE' AND Kieu='OUT' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NOT NULL AND MaKeHoachSanXuat IS NULL) OR (PhuongThuc='PRODUCTION_ISSUE' AND Kieu='OUT' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NOT NULL) OR (PhuongThuc='PRODUCTION_RECEIPT' AND Kieu='IN' AND MaDonMuaHang IS NULL AND MaKeHoachKinhDoanh IS NULL AND MaKeHoachSanXuat IS NOT NULL)),
  CONSTRAINT DuyNhat_YeuCauKho_1 UNIQUE (Ma),
  INDEX ChiMuc_YeuCauKho_1 (MaKho, Kieu, TrangThai),
  INDEX ChiMuc_YeuCauKho_2 (MaNguoiTao, NgayTao)
) ENGINE=InnoDB;

CREATE TABLE ChiTietYeuCauKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  GhiChu TEXT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietYeuCauKho_1 CHECK (SoLuong > 0),
  CONSTRAINT DuyNhat_ChiTietYeuCauKho_1 UNIQUE (MaYeuCauKho, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE PhieuKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Kieu VARCHAR(10) NOT NULL,
  MaYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaKho BIGINT UNSIGNED NOT NULL,
  MaNguoiGhiSo BIGINT UNSIGNED NOT NULL,
  NgayGhiSo DATETIME(6) NOT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  GhiChu TEXT NULL,
  KhoaChongLap VARCHAR(100) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_PhieuKho_1 CHECK (Kieu IN ('IN','OUT')),
  CONSTRAINT KiemTra_PhieuKho_2 CHECK (TrangThai='POSTED'),
  CONSTRAINT DuyNhat_PhieuKho_1 UNIQUE (Ma),
  CONSTRAINT DuyNhat_PhieuKho_2 UNIQUE (KhoaChongLap),
  INDEX ChiMuc_PhieuKho_1 (MaKho, Kieu, NgayGhiSo)
) ENGINE=InnoDB;

CREATE TABLE ChiTietPhieuKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaPhieuKho BIGINT UNSIGNED NOT NULL,
  MaChiTietYeuCauKho BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  NhomChatLuong VARCHAR(20) NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  LyDoChenhLech TEXT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietPhieuKho_1 CHECK (SoLuong > 0),
  CONSTRAINT KiemTra_ChiTietPhieuKho_2 CHECK (NhomChatLuong IN ('AVAILABLE','QUARANTINE')),
  CONSTRAINT DuyNhat_ChiTietPhieuKho_1 UNIQUE (MaPhieuKho, MaChiTietYeuCauKho, MaLoHang, MaViTriKho, NhomChatLuong)
) ENGINE=InnoDB;

CREATE TABLE TonKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  NhomChatLuong VARCHAR(20) NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_TonKho_1 CHECK (SoLuong >= 0),
  CONSTRAINT KiemTra_TonKho_2 CHECK (NhomChatLuong IN ('AVAILABLE','QUARANTINE')),
  CONSTRAINT DuyNhat_TonKho_1 UNIQUE (MaLoHang, MaViTriKho, NhomChatLuong)
) ENGINE=InnoDB;

CREATE TABLE DotKiemKe (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  NgayDuKien DATE NOT NULL,
  BatDauLuc DATETIME(6) NULL,
  KetThucLuc DATETIME(6) NULL,
  LoaiMatHang VARCHAR(20) NULL,
  TrangThai VARCHAR(30) NOT NULL,
  GhiChu TEXT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_DotKiemKe_1 CHECK (TrangThai IN ('PLANNED','IN_PROGRESS','COMPLETED','CLOSED','CANCELLED')),
  CONSTRAINT KiemTra_DotKiemKe_2 CHECK (LoaiMatHang IS NULL OR LoaiMatHang IN ('MATERIAL','FINISHED_PRODUCT')),
  CONSTRAINT DuyNhat_DotKiemKe_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE KhoKiemKe (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaDotKiemKe BIGINT UNSIGNED NOT NULL,
  MaKho BIGINT UNSIGNED NOT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  NgayChotSo DATETIME(6) NULL,
  NgayHoanTat DATETIME(6) NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_KhoKiemKe_1 CHECK (TrangThai IN ('PLANNED','COUNTING','COMPLETED','CLOSED')),
  CONSTRAINT DuyNhat_KhoKiemKe_1 UNIQUE (MaDotKiemKe, MaKho)
) ENGINE=InnoDB;

CREATE TABLE PhanCongKiemKe (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKhoKiemKe BIGINT UNSIGNED NOT NULL,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_PhanCongKiemKe_1 UNIQUE (MaKhoKiemKe, MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE ChiTietKiemKe (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKhoKiemKe BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  NhomChatLuong VARCHAR(20) NOT NULL,
  SoLuongHeThong DECIMAL(18,3) NOT NULL,
  SoLuongThucTe DECIMAL(18,3) NULL,
  MaNguoiDem BIGINT UNSIGNED NULL,
  NgayDem DATETIME(6) NULL,
  NguyenNhan TEXT NULL,
  TrangThaiXuLy VARCHAR(30) NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietKiemKe_1 CHECK (SoLuongHeThong >= 0),
  CONSTRAINT KiemTra_ChiTietKiemKe_2 CHECK (SoLuongThucTe IS NULL OR SoLuongThucTe >= 0),
  CONSTRAINT KiemTra_ChiTietKiemKe_3 CHECK (NhomChatLuong IN ('AVAILABLE','QUARANTINE')),
  CONSTRAINT KiemTra_ChiTietKiemKe_4 CHECK (TrangThaiXuLy IN ('NONE','PENDING_APPROVAL','RESOLVED')),
  CONSTRAINT DuyNhat_ChiTietKiemKe_1 UNIQUE (MaKhoKiemKe, MaLoHang, MaViTriKho, NhomChatLuong)
) ENGINE=InnoDB;

CREATE TABLE BienBanKiemKe (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaKhoKiemKe BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  NhanXet TEXT NOT NULL,
  NgayGui DATETIME(6) NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_BienBanKiemKe_1 CHECK (TrangThai IN ('DRAFT','SUBMITTED')),
  CONSTRAINT DuyNhat_BienBanKiemKe_1 UNIQUE (Ma),
  CONSTRAINT DuyNhat_BienBanKiemKe_2 UNIQUE (MaKhoKiemKe)
) ENGINE=InnoDB;

CREATE TABLE DeXuatXuLy (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  Kieu VARCHAR(30) NOT NULL,
  MaChiTietKiemTraChatLuong BIGINT UNSIGNED NULL,
  MaChiTietKiemKe BIGINT UNSIGNED NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  HanhDong VARCHAR(30) NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  LyDo TEXT NOT NULL,
  GhiChuXuLy TEXT NOT NULL,
  TrangThai VARCHAR(30) NOT NULL,
  MaNguoiDuyet BIGINT UNSIGNED NULL,
  NgayDuyet DATETIME(6) NULL,
  LyDoTuChoi TEXT NULL,
  NgayApDung DATETIME(6) NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_DeXuatXuLy_1 CHECK (SoLuong > 0),
  CONSTRAINT KiemTra_DeXuatXuLy_2 CHECK (Kieu IN ('QC_FAILURE','STOCKTAKE_DIFFERENCE')),
  CONSTRAINT KiemTra_DeXuatXuLy_3 CHECK (HanhDong IN ('ADJUST_TO_ACTUAL','SCRAP','RETURN_SUPPLIER','RELEASE')),
  CONSTRAINT KiemTra_DeXuatXuLy_4 CHECK (TrangThai IN ('PENDING_APPROVAL','APPROVED','REJECTED','APPLIED')),
  CONSTRAINT KiemTra_DeXuatXuLy_5 CHECK ((Kieu='QC_FAILURE' AND MaChiTietKiemTraChatLuong IS NOT NULL AND MaChiTietKiemKe IS NULL) OR (Kieu='STOCKTAKE_DIFFERENCE' AND MaChiTietKiemTraChatLuong IS NULL AND MaChiTietKiemKe IS NOT NULL)),
  CONSTRAINT DuyNhat_DeXuatXuLy_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE PhanBoXuLy (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaDeXuatXuLy BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_PhanBoXuLy_1 CHECK (SoLuong > 0),
  CONSTRAINT DuyNhat_PhanBoXuLy_1 UNIQUE (MaDeXuatXuLy, MaViTriKho)
) ENGINE=InnoDB;

CREATE TABLE BienDongKho (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  MaViTriKho BIGINT UNSIGNED NOT NULL,
  NhomChatLuong VARCHAR(20) NOT NULL,
  BienDongSoLuong DECIMAL(18,3) NOT NULL,
  MaChiTietPhieuKho BIGINT UNSIGNED NULL,
  MaDeXuatXuLy BIGINT UNSIGNED NULL,
  MaChiTietKiemKe BIGINT UNSIGNED NULL,
  NgayGhiSo DATETIME(6) NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  KhoaNghiepVu VARCHAR(150) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_BienDongKho_1 CHECK (BienDongSoLuong <> 0),
  CONSTRAINT KiemTra_BienDongKho_2 CHECK (NhomChatLuong IN ('AVAILABLE','QUARANTINE')),
  CONSTRAINT KiemTra_BienDongKho_3 CHECK ((MaChiTietPhieuKho IS NOT NULL) + (MaDeXuatXuLy IS NOT NULL) + (MaChiTietKiemKe IS NOT NULL) = 1),
  CONSTRAINT DuyNhat_BienDongKho_1 UNIQUE (KhoaNghiepVu),
  INDEX ChiMuc_BienDongKho_1 (MaLoHang, MaViTriKho, NgayGhiSo),
  INDEX ChiMuc_BienDongKho_2 (NgayGhiSo)
) ENGINE=InnoDB;

CREATE TABLE CongViec (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  TieuDe VARCHAR(200) NOT NULL,
  MoTa TEXT NULL,
  BatDauLuc DATETIME(6) NOT NULL,
  KetThucLuc DATETIME(6) NOT NULL,
  MucDoUuTien VARCHAR(20) NOT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  MaDotKiemKe BIGINT UNSIGNED NULL,
  MaDonMuaHang BIGINT UNSIGNED NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_CongViec_1 CHECK (KetThucLuc > BatDauLuc),
  CONSTRAINT KiemTra_CongViec_2 CHECK (MucDoUuTien IN ('LOW','NORMAL','HIGH')),
  CONSTRAINT KiemTra_CongViec_3 CHECK (TrangThai IN ('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED')),
  CONSTRAINT DuyNhat_CongViec_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE PhanCongCongViec (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaCongViec BIGINT UNSIGNED NOT NULL,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_PhanCongCongViec_1 UNIQUE (MaCongViec, MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE BaoCaoSanXuat (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaKeHoachSanXuat BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  GhiChu TEXT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  NgayGui DATETIME(6) NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_BaoCaoSanXuat_1 CHECK (TrangThai IN ('DRAFT','SUBMITTED')),
  CONSTRAINT DuyNhat_BaoCaoSanXuat_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE ChiTietBaoCaoSanXuat (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaBaoCaoSanXuat BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuongHienCo DECIMAL(18,3) NOT NULL,
  SoLuongCan DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ChiTietBaoCaoSanXuat_1 CHECK (SoLuongHienCo >= 0),
  CONSTRAINT KiemTra_ChiTietBaoCaoSanXuat_2 CHECK (SoLuongCan > 0),
  CONSTRAINT DuyNhat_ChiTietBaoCaoSanXuat_1 UNIQUE (MaBaoCaoSanXuat, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE BaoCaoThanhPham (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Ma VARCHAR(40) NOT NULL,
  MaKeHoachSanXuat BIGINT UNSIGNED NOT NULL,
  MaNguoiTao BIGINT UNSIGNED NOT NULL,
  NgayHoanThanh DATE NOT NULL,
  GhiChu TEXT NULL,
  TrangThai VARCHAR(20) NOT NULL,
  NgayGui DATETIME(6) NULL,
  PhienBan INT NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_BaoCaoThanhPham_1 CHECK (TrangThai IN ('DRAFT','SUBMITTED')),
  CONSTRAINT DuyNhat_BaoCaoThanhPham_1 UNIQUE (Ma)
) ENGINE=InnoDB;

CREATE TABLE ThanhPhamBaoCao (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaBaoCaoThanhPham BIGINT UNSIGNED NOT NULL,
  MaLoHang BIGINT UNSIGNED NOT NULL,
  SoLuong DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_ThanhPhamBaoCao_1 CHECK (SoLuong > 0),
  CONSTRAINT DuyNhat_ThanhPhamBaoCao_1 UNIQUE (MaBaoCaoThanhPham, MaLoHang),
  CONSTRAINT DuyNhat_ThanhPhamBaoCao_2 UNIQUE (MaLoHang)
) ENGINE=InnoDB;

CREATE TABLE NguyenLieuSuDung (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaBaoCaoThanhPham BIGINT UNSIGNED NOT NULL,
  MaMatHang BIGINT UNSIGNED NOT NULL,
  SoLuongSuDung DECIMAL(18,3) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT KiemTra_NguyenLieuSuDung_1 CHECK (SoLuongSuDung > 0),
  CONSTRAINT DuyNhat_NguyenLieuSuDung_1 UNIQUE (MaBaoCaoThanhPham, MaMatHang)
) ENGINE=InnoDB;

CREATE TABLE ThongBao (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  TieuDeThongBao VARCHAR(200) NOT NULL,
  NoiDung TEXT NOT NULL,
  LoaiTaiNguyen VARCHAR(50) NOT NULL,
  MaTaiNguyen BIGINT UNSIGNED NOT NULL,
  NgayDoc DATETIME(6) NULL,
  KhoaThongBao VARCHAR(150) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_ThongBao_1 UNIQUE (MaNguoiDung, KhoaThongBao),
  INDEX ChiMuc_ThongBao_1 (MaNguoiDung, NgayDoc, NgayTao)
) ENGINE=InnoDB;

CREATE TABLE NhatKyHeThong (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaNguoiThucHien BIGINT UNSIGNED NULL,
  LoaiTaiNguyen VARCHAR(50) NOT NULL,
  MaTaiNguyen BIGINT UNSIGNED NOT NULL,
  HanhDong VARCHAR(50) NOT NULL,
  DuLieuTruoc JSON NULL,
  DuLieuSau JSON NULL,
  MaYeuCau VARCHAR(50) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX ChiMuc_NhatKyHeThong_1 (LoaiTaiNguyen, MaTaiNguyen, NgayTao)
) ENGINE=InnoDB;

CREATE TABLE YeuCauChongLap (
  MaBanGhi BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung BIGINT UNSIGNED NOT NULL,
  ThaoTac VARCHAR(100) NOT NULL,
  KhoaChongLap VARCHAR(100) NOT NULL,
  MaBamYeuCau CHAR(64) NOT NULL,
  MaPhanHoi SMALLINT NOT NULL,
  NoiDungPhanHoi JSON NOT NULL,
  HetHanLuc DATETIME(6) NOT NULL,
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT DuyNhat_YeuCauChongLap_1 UNIQUE (MaNguoiDung, ThaoTac, KhoaChongLap)
) ENGINE=InnoDB;

ALTER TABLE NguoiDungVaiTro ADD CONSTRAINT KhoaNgoai_NguoiDungVaiTro_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguoiDungVaiTro ADD CONSTRAINT KhoaNgoai_NguoiDungVaiTro_MaVaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KhachHang ADD CONSTRAINT KhoaNgoai_KhachHang_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguoiDungXuong ADD CONSTRAINT KhoaNgoai_NguoiDungXuong_MaXuong FOREIGN KEY (MaXuong) REFERENCES Xuong(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguoiDungXuong ADD CONSTRAINT KhoaNgoai_NguoiDungXuong_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ViTriKho ADD CONSTRAINT KhoaNgoai_ViTriKho_MaKho FOREIGN KEY (MaKho) REFERENCES Kho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MatHang ADD CONSTRAINT KhoaNgoai_MatHang_MaLoaiHang FOREIGN KEY (MaLoaiHang) REFERENCES LoaiHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MatHang ADD CONSTRAINT KhoaNgoai_MatHang_MaDonViTinh FOREIGN KEY (MaDonViTinh) REFERENCES DonViTinh(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonHang ADD CONSTRAINT KhoaNgoai_DonHang_MaKhachHang FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonHang ADD CONSTRAINT KhoaNgoai_DonHang_MaNguoiTiepNhan FOREIGN KEY (MaNguoiTiepNhan) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonHang ADD CONSTRAINT KhoaNgoai_DonHang_MaNguoiDuyet FOREIGN KEY (MaNguoiDuyet) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietDonHang ADD CONSTRAINT KhoaNgoai_ChiTietDonHang_MaDonHang FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietDonHang ADD CONSTRAINT KhoaNgoai_ChiTietDonHang_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_MaNhaCungCap FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_MaKhachHang FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_MaDonHang FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_KeHoachKinhDoanh_MaNguoiDuyet FOREIGN KEY (MaNguoiDuyet) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_ChiTietKeHoachKinhDoanh_MaKeHoachKinhDoanh FOREIGN KEY (MaKeHoachKinhDoanh) REFERENCES KeHoachKinhDoanh(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKeHoachKinhDoanh ADD CONSTRAINT KhoaNgoai_ChiTietKeHoachKinhDoanh_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonMuaHang ADD CONSTRAINT KhoaNgoai_DonMuaHang_MaKeHoachKinhDoanh FOREIGN KEY (MaKeHoachKinhDoanh) REFERENCES KeHoachKinhDoanh(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonMuaHang ADD CONSTRAINT KhoaNgoai_DonMuaHang_MaNhaCungCap FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DonMuaHang ADD CONSTRAINT KhoaNgoai_DonMuaHang_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietDonMuaHang ADD CONSTRAINT KhoaNgoai_ChiTietDonMuaHang_MaDonMuaHang FOREIGN KEY (MaDonMuaHang) REFERENCES DonMuaHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietDonMuaHang ADD CONSTRAINT KhoaNgoai_ChiTietDonMuaHang_MaChiTietKeHoachKinhDoanh FOREIGN KEY (MaChiTietKeHoachKinhDoanh) REFERENCES ChiTietKeHoachKinhDoanh(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietDonMuaHang ADD CONSTRAINT KhoaNgoai_ChiTietDonMuaHang_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachSanXuat ADD CONSTRAINT KhoaNgoai_KeHoachSanXuat_MaDonHang FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachSanXuat ADD CONSTRAINT KhoaNgoai_KeHoachSanXuat_MaXuong FOREIGN KEY (MaXuong) REFERENCES Xuong(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KeHoachSanXuat ADD CONSTRAINT KhoaNgoai_KeHoachSanXuat_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ThanhPhamKeHoach ADD CONSTRAINT KhoaNgoai_ThanhPhamKeHoach_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ThanhPhamKeHoach ADD CONSTRAINT KhoaNgoai_ThanhPhamKeHoach_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguyenLieuKeHoach ADD CONSTRAINT KhoaNgoai_NguyenLieuKeHoach_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguyenLieuKeHoach ADD CONSTRAINT KhoaNgoai_NguyenLieuKeHoach_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LoHang ADD CONSTRAINT KhoaNgoai_LoHang_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LoHang ADD CONSTRAINT KhoaNgoai_LoHang_MaChiTietDonMuaHang FOREIGN KEY (MaChiTietDonMuaHang) REFERENCES ChiTietDonMuaHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LoHang ADD CONSTRAINT KhoaNgoai_LoHang_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhieuKiemTraChatLuong ADD CONSTRAINT KhoaNgoai_PhieuKiemTraChatLuong_MaNguoiKiemTra FOREIGN KEY (MaNguoiKiemTra) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemTraChatLuong ADD CONSTRAINT KhoaNgoai_ChiTietKiemTraChatLuong_MaPhieuKiemTraChatLuong FOREIGN KEY (MaPhieuKiemTraChatLuong) REFERENCES PhieuKiemTraChatLuong(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemTraChatLuong ADD CONSTRAINT KhoaNgoai_ChiTietKiemTraChatLuong_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaDonMuaHang FOREIGN KEY (MaDonMuaHang) REFERENCES DonMuaHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaKeHoachKinhDoanh FOREIGN KEY (MaKeHoachKinhDoanh) REFERENCES KeHoachKinhDoanh(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaXuong FOREIGN KEY (MaXuong) REFERENCES Xuong(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaKho FOREIGN KEY (MaKho) REFERENCES Kho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauKho ADD CONSTRAINT KhoaNgoai_YeuCauKho_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietYeuCauKho ADD CONSTRAINT KhoaNgoai_ChiTietYeuCauKho_MaYeuCauKho FOREIGN KEY (MaYeuCauKho) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietYeuCauKho ADD CONSTRAINT KhoaNgoai_ChiTietYeuCauKho_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhieuKho ADD CONSTRAINT KhoaNgoai_PhieuKho_MaYeuCauKho FOREIGN KEY (MaYeuCauKho) REFERENCES YeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhieuKho ADD CONSTRAINT KhoaNgoai_PhieuKho_MaKho FOREIGN KEY (MaKho) REFERENCES Kho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhieuKho ADD CONSTRAINT KhoaNgoai_PhieuKho_MaNguoiGhiSo FOREIGN KEY (MaNguoiGhiSo) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietPhieuKho ADD CONSTRAINT KhoaNgoai_ChiTietPhieuKho_MaPhieuKho FOREIGN KEY (MaPhieuKho) REFERENCES PhieuKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietPhieuKho ADD CONSTRAINT KhoaNgoai_ChiTietPhieuKho_MaChiTietYeuCauKho FOREIGN KEY (MaChiTietYeuCauKho) REFERENCES ChiTietYeuCauKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietPhieuKho ADD CONSTRAINT KhoaNgoai_ChiTietPhieuKho_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietPhieuKho ADD CONSTRAINT KhoaNgoai_ChiTietPhieuKho_MaViTriKho FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TonKho ADD CONSTRAINT KhoaNgoai_TonKho_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TonKho ADD CONSTRAINT KhoaNgoai_TonKho_MaViTriKho FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DotKiemKe ADD CONSTRAINT KhoaNgoai_DotKiemKe_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KhoKiemKe ADD CONSTRAINT KhoaNgoai_KhoKiemKe_MaDotKiemKe FOREIGN KEY (MaDotKiemKe) REFERENCES DotKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE KhoKiemKe ADD CONSTRAINT KhoaNgoai_KhoKiemKe_MaKho FOREIGN KEY (MaKho) REFERENCES Kho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanCongKiemKe ADD CONSTRAINT KhoaNgoai_PhanCongKiemKe_MaKhoKiemKe FOREIGN KEY (MaKhoKiemKe) REFERENCES KhoKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanCongKiemKe ADD CONSTRAINT KhoaNgoai_PhanCongKiemKe_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemKe ADD CONSTRAINT KhoaNgoai_ChiTietKiemKe_MaKhoKiemKe FOREIGN KEY (MaKhoKiemKe) REFERENCES KhoKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemKe ADD CONSTRAINT KhoaNgoai_ChiTietKiemKe_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemKe ADD CONSTRAINT KhoaNgoai_ChiTietKiemKe_MaViTriKho FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietKiemKe ADD CONSTRAINT KhoaNgoai_ChiTietKiemKe_MaNguoiDem FOREIGN KEY (MaNguoiDem) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienBanKiemKe ADD CONSTRAINT KhoaNgoai_BienBanKiemKe_MaKhoKiemKe FOREIGN KEY (MaKhoKiemKe) REFERENCES KhoKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienBanKiemKe ADD CONSTRAINT KhoaNgoai_BienBanKiemKe_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeXuatXuLy ADD CONSTRAINT KhoaNgoai_DeXuatXuLy_MaChiTietKiemTraChatLuong FOREIGN KEY (MaChiTietKiemTraChatLuong) REFERENCES ChiTietKiemTraChatLuong(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeXuatXuLy ADD CONSTRAINT KhoaNgoai_DeXuatXuLy_MaChiTietKiemKe FOREIGN KEY (MaChiTietKiemKe) REFERENCES ChiTietKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeXuatXuLy ADD CONSTRAINT KhoaNgoai_DeXuatXuLy_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DeXuatXuLy ADD CONSTRAINT KhoaNgoai_DeXuatXuLy_MaNguoiDuyet FOREIGN KEY (MaNguoiDuyet) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanBoXuLy ADD CONSTRAINT KhoaNgoai_PhanBoXuLy_MaDeXuatXuLy FOREIGN KEY (MaDeXuatXuLy) REFERENCES DeXuatXuLy(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanBoXuLy ADD CONSTRAINT KhoaNgoai_PhanBoXuLy_MaViTriKho FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaViTriKho FOREIGN KEY (MaViTriKho) REFERENCES ViTriKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaChiTietPhieuKho FOREIGN KEY (MaChiTietPhieuKho) REFERENCES ChiTietPhieuKho(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaDeXuatXuLy FOREIGN KEY (MaDeXuatXuLy) REFERENCES DeXuatXuLy(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaChiTietKiemKe FOREIGN KEY (MaChiTietKiemKe) REFERENCES ChiTietKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BienDongKho ADD CONSTRAINT KhoaNgoai_BienDongKho_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CongViec ADD CONSTRAINT KhoaNgoai_CongViec_MaDotKiemKe FOREIGN KEY (MaDotKiemKe) REFERENCES DotKiemKe(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CongViec ADD CONSTRAINT KhoaNgoai_CongViec_MaDonMuaHang FOREIGN KEY (MaDonMuaHang) REFERENCES DonMuaHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CongViec ADD CONSTRAINT KhoaNgoai_CongViec_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanCongCongViec ADD CONSTRAINT KhoaNgoai_PhanCongCongViec_MaCongViec FOREIGN KEY (MaCongViec) REFERENCES CongViec(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PhanCongCongViec ADD CONSTRAINT KhoaNgoai_PhanCongCongViec_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BaoCaoSanXuat ADD CONSTRAINT KhoaNgoai_BaoCaoSanXuat_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BaoCaoSanXuat ADD CONSTRAINT KhoaNgoai_BaoCaoSanXuat_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietBaoCaoSanXuat ADD CONSTRAINT KhoaNgoai_ChiTietBaoCaoSanXuat_MaBaoCaoSanXuat FOREIGN KEY (MaBaoCaoSanXuat) REFERENCES BaoCaoSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ChiTietBaoCaoSanXuat ADD CONSTRAINT KhoaNgoai_ChiTietBaoCaoSanXuat_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BaoCaoThanhPham ADD CONSTRAINT KhoaNgoai_BaoCaoThanhPham_MaKeHoachSanXuat FOREIGN KEY (MaKeHoachSanXuat) REFERENCES KeHoachSanXuat(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BaoCaoThanhPham ADD CONSTRAINT KhoaNgoai_BaoCaoThanhPham_MaNguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ThanhPhamBaoCao ADD CONSTRAINT KhoaNgoai_ThanhPhamBaoCao_MaBaoCaoThanhPham FOREIGN KEY (MaBaoCaoThanhPham) REFERENCES BaoCaoThanhPham(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ThanhPhamBaoCao ADD CONSTRAINT KhoaNgoai_ThanhPhamBaoCao_MaLoHang FOREIGN KEY (MaLoHang) REFERENCES LoHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguyenLieuSuDung ADD CONSTRAINT KhoaNgoai_NguyenLieuSuDung_MaBaoCaoThanhPham FOREIGN KEY (MaBaoCaoThanhPham) REFERENCES BaoCaoThanhPham(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NguyenLieuSuDung ADD CONSTRAINT KhoaNgoai_NguyenLieuSuDung_MaMatHang FOREIGN KEY (MaMatHang) REFERENCES MatHang(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ThongBao ADD CONSTRAINT KhoaNgoai_ThongBao_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE NhatKyHeThong ADD CONSTRAINT KhoaNgoai_NhatKyHeThong_MaNguoiThucHien FOREIGN KEY (MaNguoiThucHien) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE YeuCauChongLap ADD CONSTRAINT KhoaNgoai_YeuCauChongLap_MaNguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaBanGhi) ON DELETE RESTRICT ON UPDATE RESTRICT;


CREATE TABLE PhienDangNhap (
  MaPhien VARCHAR(128) NOT NULL PRIMARY KEY,
  HetHanLuc BIGINT UNSIGNED NOT NULL,
  DuLieu JSON NOT NULL,
  INDEX ChiMuc_PhienDangNhap_HetHanLuc (HetHanLuc)
) ENGINE=InnoDB;

CREATE TABLE LanThuDangNhap (
  KhoaLanThu CHAR(64) NOT NULL PRIMARY KEY,
  BatDauCuaSo BIGINT UNSIGNED NOT NULL,
  SoLan INT UNSIGNED NOT NULL,
  CONSTRAINT KiemTra_LanThuDangNhap CHECK (SoLan >= 0),
  INDEX ChiMuc_LanThuDangNhap_BatDauCuaSo (BatDauCuaSo)
) ENGINE=InnoDB;
